apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lm5dggzq0-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lm5dggzq0-python 
  name: lm5dggzq0-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lm5dggzq0-python 
