apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lm5dggzq0-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0357972cbe.x8xz.p3.openshiftapps.com/rhtap/rhtap-qe:8a1183bdc15d6eee32205cab2d81892c07148903@sha256:c66a5874578f9130f020cdb0293175dfe978fb14df992040e36255b4631d8b1b
          name: container-image
